### ISSUE TITLE
Confusing name `with_arg`

### ISSUE THREAD

**Issue by lastmjs** [dfinity/agent-rs#224]
Hey!

I just had a pretty hard time figuring out how to use https://agent-rust.netlify.app/ic_agent/agent/struct.updatebuilder#method.with_arg

Because the function is called `with_arg`, I assumed I had to call it multiple times in the builder pattern to continue adding args. Eventually I tried adding multiple args into `with_arg`, and it finally worked.

Consider changing the name to `with_args`?

**Comment by adamspofford-dfinity** [comment]
A canister function takes exactly one argument. For canisters that encode their messages with Candid, which is not all of them, that argument is a Candid-encoded tuple of other Candid types. This naming is mirrored in `dfx` (`--argument`), `cdk-rs` (`arg_data`), and in the IC system interface (`msg_arg_data_copy`). For functions that interact with Candid, instead of arbitrary byte blobs, the `ArgumentEncoder` interface is used which makes sure you declare it as a tuple, so there's no confusion about whether it's a single argument or multiple arguments.

Closing as wontfix, but if you feel the [smartcontracts.org](https://smartcontracts.org) documentation could have better informed you about this distinction, feel free to open an issue on dfinity/docs describing how.
